include:
  - board: nice_nano
    shield: seagull
  - board: nice_nano
    shield: seagull
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: seagull_studio
  - board: nice_nano
    shield: settings_reset
